### ISSUE TITLE
Headscale crash with unknown cause

### ISSUE THREAD

**Issue by winterheart** [juanfont/headscale#1862]
## Bug description

Periodically headscale crashes with dump in logs:

```
fatal error: concurrent map read and map write

goroutine 106672824 [running]:
github.com/juanfont/headscale/hscontrol.(*Headscale).handlePoll(0xc0002fc0e0, {0x2294590, _}, {_, _}, _, {0x57, {0xc007b4ba58, 0x4}, 0x1, ...})
        /home/runner/work/headscale/headscale/hscontrol/poll.go:455 +0x2169
github.com/juanfont/headscale/hscontrol.(*noiseServer).NoisePollNetMapHandler(0xc0018d1830, {0x2294590, 0xc00411c8b8}, 0xc0010626c0)
        /home/runner/work/headscale/headscale/hscontrol/poll_noise.go:95 +0x596
net/http.HandlerFunc.ServeHTTP(0xc0010625a0?, {0x2294590?, 0xc00411c8b8?}, 0xc0019a0000?)
        /nix/store/88y9r33p3j8f7bc8sqiy9jdlk7yqfrlg-go-1.22.0/share/go/src/net/http/server.go:2166 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0051800c0, {0x2294590, 0xc00411c8b8}, 0xc001991e60)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
golang.org/x/net/http2.(*serverConn).runHandler(0x4498fd?, 0x0?, 0x0?, 0xc0013a7400?)
        /home/runner/go/pkg/mod/golang.org/x/net@v0.21.0/http2/server.go:2368 +0xbb
created by golang.org/x/net/http2.(*serverConn).scheduleHandler in goroutine 106672803
        /home/runner/go/pkg/mod/golang.org/x/net@v0.21.0/http2/server.go:2303 +0x21d
```

## Environment

- OS: Gentoo Linux
- Headscale version: v0.23.0-alpha5
- Tailscale version: any

- [ ] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

**Comment by kradalby** [comment]
Could you please try the newest alpha (https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha6) and report back?
